"""ml/dyno_classifier.py -- fault classifier for a MEASURED surface
dynamometer card, trained on SYNTHETIC cards generated by the physics twin
(twin.dyno.compute_cards()), not on any real field data.

Why synthetic training data. PS SIH26120 asks the twin to ingest a measured
surface card (position vs. load) from the field and return a fault read --
full pump / fluid pound / gas interference / heavy-oil viscous drag / rod
float (carrier-bar separation). Oil India has not handed over a real card, so
this module sweeps twin.dyno.compute_cards() (docs/model-improvement/
DYNO_CARD_MODEL.md has the fault signatures and the JSON shape) over spm, oil
viscosity, pump fillage, water cut, the gas-interference option and small
rod-string geometry perturbations, adds measurement noise and irregular
resampling to imitate a real card reader, and trains a RandomForestClassifier
on shape features of the SURFACE card alone (position_m, load_surface_kN --
what a beam-inclinometer dynamometer actually records; the downhole/pump card
computed alongside it is only used to derive the ground-truth label via
compute_cards()'s own card_type, exactly as a specialist would read a
downhole card off a measured surface one).

*** DOMAIN-SHIFT CAVEAT ***
This classifier has NEVER seen a real dynamometer card. It is trained on
cards computed from a [TYPICAL] 1" x 7/8" rod string over 1,150 m, a
crank-pitman surface unit and a single viscous-drag law (see the twin.dyno
module docstring and DYNO_CARD_MODEL.md section 6, "Known limits") -- a real
Baghewala string, unit geometry and valve wear will differ. Treat every
prediction as a first read to confirm with a pump specialist, not a
diagnosis. The first real measured card Oil India shares should be used to
re-fit this classifier (same idea as twin/calibrate.py's field recalibration
of the reservoir model) -- retrain with `python -m ml.dyno_classifier
--train`.

Features (`card_features()`, `FEATURE_NAMES`, 143 total) -- all computed on
the card AFTER converting to canonical units (m, kN) and normalising its
bounding box to [0, 1] x [0, 1], so they do not depend on the absolute stroke
length or load scale of a particular well/rod string, only on card SHAPE:
  * up_0..up_63, dn_0..dn_63 (128) -- normalised load vs. normalised position,
    resampled to 64 points on each of the up-stroke and down-stroke branches
    (branch split follows twin.dyno._branches's own convention: split at the
    position argmax/argmin, sort each half by position).
  * area_frac -- shoelace loop area / (position range x load range): how much
    of its own bounding box the loop fills (a thin rod-float egg vs. a fat
    parallelogram).
  * aspect_ratio_kN_per_m -- load range / position range, in the canonical
    units (not scale-free across wells, but consistent once units are fixed).
  * min_over_max, mean_over_max, min_over_mean -- load ratios (scale-free by
    construction: a ratio of two loads in the same unit).
  * downstroke_slope_mid -- linear-fit slope of the normalised downstroke
    over the middle 25-75% of the stroke (inertia peaks at the stroke ends,
    drag at mid-stroke -- DYNO_CARD_MODEL.md section 3), fully dimensionless.
  * zero_load_frac -- fraction of the (closed, normalised) loop's points at or
    below 5% of the load range: the rod-float / carrier-separation tell.
  * fourier_mag_1..8 -- magnitudes of the first 8 non-DC Fourier coefficients
    of the closed contour z(t) = position_norm(t) + i*load_norm(t), resampled
    to a uniform ARC-LENGTH parametrisation (robust to irregular sampling
    density) -- captures overall loop shape independent of the branch split
    or where around the loop the recording happened to start.

Usage:
    python -m ml.dyno_classifier --train                 # regenerate + retrain
    python -m ml.dyno_classifier --demo                  # classify the 8 baked cards
"""
from __future__ import annotations

import argparse
import json
import math
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import joblib
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split

ML_DIR = Path(__file__).resolve().parent
ROOT = ML_DIR.parent
MODELS_DIR = ML_DIR / "models"
MODEL_PATH = MODELS_DIR / "dyno_clf.joblib"
METRICS_PATH = MODELS_DIR / "dyno_clf_metrics.json"
BAKED_CARDS_PATH = MODELS_DIR / "dyno_cards.json"
DEFAULT_PARAMS_PATH = ROOT / "params" / "field_params.json"

SEED = 42
CARD_TYPES = ["full_pump", "fluid_pound", "gas_interference", "heavy_oil_viscous", "rod_float"]

# --------------------------------------------------------------------------
# Unit handling -- accept position_m/position_in, load_kN/load_klbf, and
# auto-detect by magnitude when the caller doesn't say.
# --------------------------------------------------------------------------
M_PER_IN = 0.0254
KN_PER_KLBF = 4.4482216152605
MIN_POINTS = 6
# Typical Baghewala-scale cards run 0.5-6 m of stroke, 20-280 in; typical
# loads run 0-150 kN (DYNO_CARD_MODEL.md section 5), 0-33 klbf. A position
# range above this many "metres" is almost certainly inches; a load whose
# largest magnitude is below this many "kN" is almost certainly klbf.
POS_RANGE_IN_GUESS_M = 12.0
LOAD_KLBF_GUESS_MAX = 40.0

_POSITION_COL_HINTS = {"position_m": "m", "pos_m": "m", "x_m": "m",
                        "position_in": "in", "pos_in": "in", "x_in": "in",
                        "position": None, "pos": None, "x": None}
_LOAD_COL_HINTS = {"load_kn": "kN", "prl_kn": "kN", "y_kn": "kN",
                    "load_klbf": "klbf", "prl_klbf": "klbf", "y_klbf": "klbf",
                    "load": None, "prl": None, "y": None}


def _detect_position_unit(position_raw: np.ndarray) -> str:
    return "in" if float(np.ptp(position_raw)) > POS_RANGE_IN_GUESS_M else "m"


def _detect_load_unit(load_raw: np.ndarray) -> str:
    return "klbf" if float(np.max(np.abs(load_raw))) < LOAD_KLBF_GUESS_MAX else "kN"


def _resolve_units(units: Any, position_raw: np.ndarray, load_raw: np.ndarray) -> tuple[str, str, bool]:
    """Returns (position_unit, load_unit, guessed) -- guessed is True if
    EITHER unit had to be inferred by magnitude rather than stated."""
    pos_unit = load_unit = None
    if isinstance(units, str):
        parts = [p.strip().lower() for p in units.split(",")]
        if len(parts) == 2:
            pos_unit, load_unit = parts
    elif isinstance(units, dict):
        pos_unit = (units.get("position") or units.get("position_unit") or None)
        load_unit = (units.get("load") or units.get("load_unit") or None)
        pos_unit = pos_unit.lower() if pos_unit else None
        load_unit = load_unit.lower() if load_unit else None
    guessed_pos = pos_unit not in ("m", "in")
    guessed_load = load_unit not in ("kn", "klbf")
    if guessed_pos:
        pos_unit = _detect_position_unit(position_raw)
    if guessed_load:
        load_unit = _detect_load_unit(load_raw)
    return pos_unit, ("klbf" if load_unit == "klbf" else "kN"), (guessed_pos or guessed_load)


def _to_canonical(position_raw: np.ndarray, load_raw: np.ndarray, units: Any = None):
    pos_unit, load_unit, guessed = _resolve_units(units, position_raw, load_raw)
    pos_m = position_raw * M_PER_IN if pos_unit == "in" else position_raw
    load_kN = load_raw * KN_PER_KLBF if load_unit == "klbf" else load_raw
    return pos_m, load_kN, {"position": pos_unit, "load": load_unit, "guessed": guessed}


def _validate_raw(position, load) -> tuple[np.ndarray, np.ndarray]:
    position = np.asarray(position, dtype=float).reshape(-1)
    load = np.asarray(load, dtype=float).reshape(-1)
    if len(position) != len(load):
        raise ValueError(f"position and load must be the same length (got {len(position)} vs {len(load)})")
    if len(position) < MIN_POINTS:
        raise ValueError(f"need at least {MIN_POINTS} points to read a dynamometer card (got {len(position)})")
    if not np.all(np.isfinite(position)) or not np.all(np.isfinite(load)):
        raise ValueError("position/load contain NaN or infinite values")
    if float(np.ptp(position)) <= 0:
        raise ValueError("position has zero range -- not a valid stroke")
    if float(np.ptp(load)) <= 0:
        raise ValueError("load has zero range -- not a valid card (no load variation)")
    return position, load


def parse_card_table(text: str) -> tuple[np.ndarray, np.ndarray, dict]:
    """Parse a CSV (with header) or a plain pasted two-column table (no
    header, comma/tab/whitespace separated) into (position, load, units).
    `units` has explicit "m"/"in"/"kN"/"klbf" values when the header names
    them, else None (caller auto-detects by magnitude in `_to_canonical`)."""
    raw = str(text).strip()
    if not raw:
        raise ValueError("empty input -- no rows found")
    lines = [ln for ln in raw.replace("\r", "").split("\n") if ln.strip()]
    if not lines:
        raise ValueError("empty input -- no rows found")

    def _split(line: str) -> list[str]:
        if "," in line:
            return [c.strip() for c in line.split(",")]
        if "\t" in line:
            return [c.strip() for c in line.split("\t")]
        return line.split()

    def _is_number(tok: str) -> bool:
        try:
            float(tok)
            return True
        except ValueError:
            return False

    first = _split(lines[0])
    has_header = len(first) >= 2 and not all(_is_number(t) for t in first)
    pos_unit = load_unit = None
    if has_header:
        header = [h.strip().lower().replace(" ", "_") for h in first]
        pos_idx = load_idx = None
        for i, h in enumerate(header):
            if pos_idx is None and h in _POSITION_COL_HINTS:
                pos_idx, pos_unit = i, _POSITION_COL_HINTS[h]
            if load_idx is None and h in _LOAD_COL_HINTS:
                load_idx, load_unit = i, _LOAD_COL_HINTS[h]
        if pos_idx is None:
            pos_idx = 0
        if load_idx is None:
            load_idx = 1 if len(header) > 1 else 0
        data_lines = lines[1:]
    else:
        pos_idx, load_idx = 0, 1
        data_lines = lines

    position, load = [], []
    for ln in data_lines:
        cells = _split(ln)
        if len(cells) <= max(pos_idx, load_idx):
            continue
        try:
            p, l = float(cells[pos_idx]), float(cells[load_idx])
        except ValueError:
            continue
        position.append(p)
        load.append(l)
    if len(position) < MIN_POINTS:
        raise ValueError(f"parsed only {len(position)} numeric row(s) -- need at least {MIN_POINTS}")
    return np.asarray(position), np.asarray(load), {"position": pos_unit, "load": load_unit}


# --------------------------------------------------------------------------
# Shape features
# --------------------------------------------------------------------------
N_BRANCH_POINTS = 64
N_CONTOUR_POINTS = 128
N_FOURIER = 8

FEATURE_NAMES = (
    [f"up_{i}" for i in range(N_BRANCH_POINTS)]
    + [f"dn_{i}" for i in range(N_BRANCH_POINTS)]
    + ["area_frac", "aspect_ratio_kN_per_m", "min_over_max", "mean_over_max", "min_over_mean",
       "downstroke_slope_mid", "zero_load_frac"]
    + [f"fourier_mag_{k}" for k in range(1, N_FOURIER + 1)]
)


def _close_loop(x: np.ndarray, f: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    if math.hypot(float(x[-1] - x[0]), float(f[-1] - f[0])) > 1e-9:
        x = np.append(x, x[0])
        f = np.append(f, f[0])
    return x, f


def _branches(x: np.ndarray, f: np.ndarray):
    """Split a closed, time-ordered card loop into (up-stroke, down-stroke),
    each sorted ascending by position -- mirrors twin.dyno._branches's own
    convention (duplicated here so ml/ has no import-time dependency on
    twin/dyno.py's private helpers)."""
    n = len(x)
    i_top, i_bot = int(np.argmax(x)), int(np.argmin(x))
    up = (np.arange(i_bot, i_bot + ((i_top - i_bot) % n) + 1)) % n
    dn = (np.arange(i_top, i_top + ((i_bot - i_top) % n) + 1)) % n
    out = []
    for idx in (up, dn):
        xs, fs = x[idx], f[idx]
        o = np.argsort(xs, kind="stable")
        out.append((xs[o], fs[o]))
    return out


def _resample_branch(xs: np.ndarray, fs: np.ndarray, n: int) -> np.ndarray:
    grid = np.linspace(0.0, 1.0, n)
    return np.interp(grid, xs, fs)


def _normalize(x: np.ndarray, f: np.ndarray):
    x_min, x_max = float(x.min()), float(x.max())
    f_min, f_max = float(f.min()), float(f.max())
    x_range = max(x_max - x_min, 1e-9)
    f_range = max(f_max - f_min, 1e-9)
    return (x - x_min) / x_range, (f - f_min) / f_range, x_range, f_range


def card_features(position_m, load_kN) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Feature vector (len(FEATURE_NAMES),) for one closed card, plus the
    normalised (x_n, f_n) arrays (reused by the fillage rule)."""
    x, f = _close_loop(np.asarray(position_m, dtype=float), np.asarray(load_kN, dtype=float))
    x_n, f_n, x_range, f_range = _normalize(x, f)

    (xu, fu), (xd, fd) = _branches(x_n, f_n)
    up = _resample_branch(xu, fu, N_BRANCH_POINTS)
    dn = _resample_branch(xd, fd, N_BRANCH_POINTS)

    area = 0.5 * abs(np.sum(x[:-1] * f[1:] - x[1:] * f[:-1]))
    area_frac = area / (x_range * f_range)
    aspect_ratio = f_range / x_range

    f_max, f_min, f_mean = float(f.max()), float(f.min()), float(f.mean())
    min_over_max = f_min / f_max if f_max != 0 else 0.0
    mean_over_max = f_mean / f_max if f_max != 0 else 0.0
    min_over_mean = f_min / f_mean if abs(f_mean) > 1e-9 else 0.0

    grid = np.linspace(0.0, 1.0, N_BRANCH_POINTS)
    mid = (grid >= 0.25) & (grid <= 0.75)
    downstroke_slope = float(np.polyfit(grid[mid], dn[mid], 1)[0]) if mid.sum() >= 2 else 0.0

    zero_load_frac = float(np.mean(f_n <= 0.05))

    d = np.hypot(np.diff(x_n), np.diff(f_n))
    s = np.concatenate([[0.0], np.cumsum(d)])
    total = s[-1] if s[-1] > 0 else 1.0
    t_grid = np.linspace(0.0, 1.0, N_CONTOUR_POINTS, endpoint=False)
    x_c = np.interp(t_grid, s / total, x_n)
    f_c = np.interp(t_grid, s / total, f_n)
    Z = np.fft.fft(x_c + 1j * f_c)
    fourier_mags = (np.abs(Z[1:N_FOURIER + 1]) / N_CONTOUR_POINTS).tolist()

    feats = np.concatenate([
        up, dn,
        np.array([area_frac, aspect_ratio, min_over_max, mean_over_max, min_over_mean,
                   downstroke_slope, zero_load_frac]),
        np.array(fourier_mags),
    ])
    return feats, x_n, f_n


def _fillage_rule(x_n: np.ndarray, f_n: np.ndarray) -> float:
    """Rule-based fillage estimate from the downstroke shape alone (no
    physics reference load available for a measured card): travel, from the
    top of the stroke down, before the normalised load first crosses below
    its own mid-range (0.5) -- mirrors twin.dyno.classify_card's card_fill
    definition, using a relative threshold instead of Fo/2."""
    (_, _), (xd, fd) = _branches(x_n, f_n)
    xr, fr = xd[::-1], fd[::-1]  # top -> bottom
    below = np.nonzero(fr < 0.5)[0]
    travel = float(xr[0] - xr[below[0]]) if len(below) else 1.0
    return float(np.clip(1.0 - travel, 0.0, 1.0))


def _quality_flags(position_raw: np.ndarray, load_raw: np.ndarray, unit_guessed: bool) -> dict:
    n = len(position_raw)
    diag = math.hypot(float(np.ptp(position_raw)), float(np.ptp(load_raw))) or 1.0
    d_close = math.hypot(float(position_raw[-1] - position_raw[0]), float(load_raw[-1] - load_raw[0]))
    return {
        "too_few_points": bool(n < 20),
        "not_closed_loop": bool(d_close > 0.15 * diag),
        "unit_guess": bool(unit_guessed),
    }


# --------------------------------------------------------------------------
# Bilingual operator sentences
# --------------------------------------------------------------------------
SENTENCES = {
    "en": {
        "full_pump": "Pump barrel is filling completely each stroke ({fillage:.0f}% estimated fillage) -- healthy operation.",
        "fluid_pound": "Pump is outrunning the well's inflow -- estimated {fillage:.0f}% fillage; the plunger is falling through a partly empty barrel each stroke.",
        "gas_interference": "Free gas is cushioning the pump's release -- estimated {fillage:.0f}% fillage; effective liquid fillage likely reads lower than this.",
        "heavy_oil_viscous": "Thick, cold oil is dragging on the rods through the stroke -- higher load, not by itself a failure risk (estimated {fillage:.0f}% fillage).",
        "rod_float": "Rods are going slack (carrier-bar separation) for part of the stroke -- the pump may be running faster than the fluid can follow; consider reducing SPM.",
    },
    "hi": {
        "full_pump": "हर स्ट्रोक में पंप बैरल पूरी तरह भर रहा है (अनुमानित {fillage:.0f}% भराव) -- सामान्य संचालन।",
        "fluid_pound": "पंप कुएँ की आवक दर से तेज़ चल रहा है -- अनुमानित {fillage:.0f}% भराव; प्लंजर हर स्ट्रोक में आंशिक रूप से खाली बैरल में गिर रहा है।",
        "gas_interference": "मुक्त गैस पंप की रिहाई को नरम कर रही है -- अनुमानित {fillage:.0f}% भराव; प्रभावी तरल भराव इससे कम हो सकता है।",
        "heavy_oil_viscous": "गाढ़ा, ठंडा तेल पूरे स्ट्रोक में रॉड पर खिंचाव डाल रहा है -- भार बढ़ा है, यह अपने आप में विफलता जोखिम नहीं है (अनुमानित {fillage:.0f}% भराव)।",
        "rod_float": "स्ट्रोक के एक भाग में रॉड ढीली हो रही हैं (क्लैंप पृथक) -- पंप तरल आपूर्ति से तेज़ चल सकता है; गति (SPM) घटाने पर विचार करें।",
    },
}

MODEL_CAVEAT = (
    "Classified by a model trained on SYNTHETIC cards computed from twin.dyno.compute_cards() "
    "(a [TYPICAL] 1\" x 7/8\" rod string over 1,150 m -- docs/model-improvement/DYNO_CARD_MODEL.md), "
    "never on a real measured card. Treat this as a first read to confirm with a pump specialist, not "
    "a diagnosis -- re-fit ml/dyno_classifier.py against the first real cards Oil India shares."
)


# --------------------------------------------------------------------------
# Model load / inference
# --------------------------------------------------------------------------
_MODEL_CACHE: dict | None = None


def _load_model() -> dict:
    global _MODEL_CACHE
    if _MODEL_CACHE is None:
        if not MODEL_PATH.exists():
            raise FileNotFoundError(f"{MODEL_PATH} not found -- run `python -m ml.dyno_classifier --train` first.")
        _MODEL_CACHE = joblib.load(MODEL_PATH)
    return _MODEL_CACHE


def classify_card(position, load, units: Any = None) -> dict:
    """Classify a MEASURED surface dynamometer card.

    Args:
        position: sequence of polished-rod positions (any consistent unit).
        load: sequence of polished-rod loads (any consistent unit).
        units: None (auto-detect both by magnitude), a "position,load" string
            (e.g. "in,klbf"), or a {"position":.., "load":..} dict; either
            axis left None/unrecognised falls back to magnitude detection.

    Returns dict: card_type, probabilities (per class), fillage_est, peak_kN,
    min_kN, sentence_en, sentence_hi, quality_flags, model_caveat.

    Raises ValueError on malformed input (mismatched lengths, too few points,
    non-finite values, zero-range axis).
    """
    position_raw, load_raw = _validate_raw(position, load)
    pos_m, load_kN, unit_info = _to_canonical(position_raw, load_raw, units)
    flags = _quality_flags(pos_m, load_kN, unit_info["guessed"])
    flags["position_unit_used"] = unit_info["position"]
    flags["load_unit_used"] = unit_info["load"]

    feats, x_n, f_n = card_features(pos_m, load_kN)
    bundle = _load_model()
    clf, classes = bundle["model"], bundle["classes"]
    proba = clf.predict_proba(feats.reshape(1, -1))[0]
    card_type = classes[int(np.argmax(proba))]
    probabilities = {c: float(p) for c, p in zip(classes, proba)}

    fillage_est = _fillage_rule(x_n, f_n)
    kwargs = {"fillage": 100.0 * fillage_est}
    return {
        "card_type": card_type,
        "probabilities": probabilities,
        "fillage_est": fillage_est,
        "peak_kN": float(load_kN.max()),
        "min_kN": float(load_kN.min()),
        "sentence_en": SENTENCES["en"][card_type].format(**kwargs),
        "sentence_hi": SENTENCES["hi"][card_type].format(**kwargs),
        "quality_flags": flags,
        "model_caveat": MODEL_CAVEAT,
    }


def classify_baked_demo(scenario: str = "baseline") -> list[dict]:
    """Classify the (baseline scenario's) 4 baked cards in ml/models/
    dyno_cards.json against their own physics-derived card_type -- used by
    GET /api/dyno/classify/demo. `baseline` is picked deterministically (it
    is the console's default scenario); the other 4 (recommendation) are
    exercised individually in tests/test_dyno_classifier.py."""
    with open(BAKED_CARDS_PATH) as f:
        data = json.load(f)
    out = []
    for c in data["scenarios"][scenario]["cards"]:
        pred = classify_card(c["surface"]["position_m"], c["surface"]["load_kN"], units={"position": "m", "load": "kN"})
        out.append({
            "key": c["key"], "true_card_type": c["card_type"], "true_card_label": c["card_label"],
            "predicted_card_type": pred["card_type"], "probabilities": pred["probabilities"],
            "fillage_est": pred["fillage_est"], "true_fillage": c["pump_fillage"],
        })
    return out


# --------------------------------------------------------------------------
# Synthetic training-set generation
# --------------------------------------------------------------------------
_BASE_STROKE_M = 2.18
_BASE_DEPTH_M = 1150.0


def _strata(rng: np.random.Generator, n: int) -> list[dict]:
    """Stratified sampling plan across (spm, mu_cP, fillage, water_cut, gas)
    so every card_type is well represented -- rod_float and gas_interference
    live in corners of the box a plain uniform draw under-covers."""
    fracs = {"general": 0.30, "low_mu": 0.20, "gas": 0.15, "viscous": 0.15, "rod_float": 0.20}
    counts = {k: int(round(n * f)) for k, f in fracs.items()}
    counts["general"] += n - sum(counts.values())  # absorb rounding remainder

    def block(n_i, spm_lo, spm_hi, mu_lo, mu_hi, fill_lo, fill_hi, gas_p):
        return {
            "spm": rng.uniform(spm_lo, spm_hi, n_i),
            "mu": np.exp(rng.uniform(math.log(mu_lo), math.log(mu_hi), n_i)),
            "fillage": rng.uniform(fill_lo, fill_hi, n_i),
            "water_cut": rng.uniform(0.6, 0.95, n_i),
            "gas": rng.random(n_i) < gas_p,
        }

    blocks = [
        block(counts["general"], 2.0, 12.0, 5.0, 15000.0, 0.4, 1.0, 0.25),
        block(counts["low_mu"], 2.0, 8.0, 5.0, 300.0, 0.4, 1.0, 0.0),
        block(counts["gas"], 2.0, 10.0, 5.0, 2000.0, 0.4, 0.9, 1.0),
        block(counts["viscous"], 3.0, 9.0, 500.0, 6000.0, 0.8, 1.0, 0.0),
        block(counts["rod_float"], 7.0, 12.0, 3000.0, 15000.0, 0.6, 1.0, 0.0),
    ]
    return blocks


def generate_dataset(params: dict, n_samples: int = 3200, seed: int = SEED):
    """Sweeps twin.dyno.compute_cards() to build a labelled synthetic
    training set (>= n_samples rows, stratified across spm 2-12, mu 5-15,000
    cP log-spaced, fillage 0.4-1.0, water_cut 0.6-0.95, the gas-interference
    option, and stroke +/-10% / depth +/-15% geometry perturbations), then
    corrupts each card with 1-3% load noise, 0.5% position noise and an
    irregular resampling to ~100 points -- imitating a real card reader
    rather than the clean 200-point simulator grid. Labels are compute_
    cards()'s own rule-based card_type (DYNO_CARD_MODEL.md section 3),
    computed from BOTH the surface and pump card; only the SURFACE card
    (what a measured dynamometer records) is fed to feature extraction.

    Returns (X, y, meta) -- X: (n, len(FEATURE_NAMES)) float array, y: (n,)
    array of card_type strings, meta: dict of generation counts."""
    from twin import dyno as twin_dyno

    rng = np.random.default_rng(seed)
    blocks = _strata(rng, n_samples)

    rows, labels = [], []
    n_attempted = 0
    n_failed = 0
    for blk in blocks:
        n_i = len(blk["spm"])
        stroke_mult = rng.uniform(0.90, 1.10, n_i)
        depth_mult = rng.uniform(0.85, 1.15, n_i)
        load_noise_frac = rng.uniform(0.01, 0.03, n_i)
        for i in range(n_i):
            n_attempted += 1
            try:
                card = twin_dyno.compute_cards(
                    spm=float(blk["spm"][i]),
                    stroke_m=_BASE_STROKE_M * float(stroke_mult[i]),
                    mu_cP=float(blk["mu"][i]),
                    fillage=float(blk["fillage"][i]),
                    water_cut=float(blk["water_cut"][i]),
                    params=params,
                    depth_m=_BASE_DEPTH_M * float(depth_mult[i]),
                    gas_interference=bool(blk["gas"][i]),
                    n_points=240,
                )
            except Exception:
                n_failed += 1
                continue

            x = np.asarray(card["position_m"], dtype=float)
            f = np.asarray(card["load_surface_kN"], dtype=float)
            if not (np.all(np.isfinite(x)) and np.all(np.isfinite(f))):
                n_failed += 1
                continue

            # measurement noise
            x_noisy = x + rng.normal(0.0, 0.005 * max(np.ptp(x), 1e-6), size=x.shape)
            f_noisy = f * (1.0 + rng.normal(0.0, float(load_noise_frac[i]), size=f.shape))

            # irregular resampling to ~100 points (jittered index grid, not a
            # clean uniform re-sample of the 240-point simulator grid)
            n_target = 100
            base_idx = np.linspace(0, len(x_noisy) - 1, n_target)
            jitter = rng.uniform(-0.5 * len(x_noisy) / n_target, 0.5 * len(x_noisy) / n_target, n_target)
            sel = np.clip(np.round(base_idx + jitter), 0, len(x_noisy) - 1).astype(int)
            sel = np.unique(sel)

            try:
                feats, _, _ = card_features(x_noisy[sel], f_noisy[sel])
            except Exception:
                n_failed += 1
                continue

            rows.append(feats)
            labels.append(card["card_type"])

    X = np.vstack(rows)
    y = np.asarray(labels)
    meta = {"n_attempted": n_attempted, "n_failed": n_failed, "n_rows": len(y),
            "class_counts": {c: int((y == c).sum()) for c in sorted(set(y.tolist()))}}
    return X, y, meta


# --------------------------------------------------------------------------
# Training
# --------------------------------------------------------------------------
def train(params: dict, n_samples: int = 3200, seed: int = SEED,
          out_model: Path = MODEL_PATH, out_metrics: Path = METRICS_PATH) -> dict:
    X, y, gen_meta = generate_dataset(params, n_samples=n_samples, seed=seed)

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=seed, stratify=y
    )
    clf = RandomForestClassifier(
        n_estimators=400, max_depth=None, min_samples_leaf=2,
        class_weight="balanced_subsample", random_state=seed, n_jobs=-1,
    )
    clf.fit(X_train, y_train)
    classes = clf.classes_.tolist()

    y_pred = clf.predict(X_test)
    acc = float(accuracy_score(y_test, y_pred))
    report = classification_report(y_test, y_pred, labels=classes, output_dict=True, zero_division=0)
    per_class_f1 = {c: float(report[c]["f1-score"]) for c in classes}
    cm = confusion_matrix(y_test, y_pred, labels=classes).tolist()

    MODELS_DIR.mkdir(parents=True, exist_ok=True)
    bundle = {
        "model": clf, "classes": classes, "feature_names": FEATURE_NAMES,
        "seed": seed, "trained_at_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
    }
    joblib.dump(bundle, out_model)
    if Path(out_model) == MODEL_PATH:
        # Refresh classify_card()'s in-memory cache so a retrain takes effect
        # immediately, without waiting for the next cold `_load_model()` --
        # only when writing to the canonical path (a retrain to a scratch
        # path, e.g. a determinism test, must not disturb the live model).
        global _MODEL_CACHE
        _MODEL_CACHE = bundle

    metrics = {
        "trained_at_utc": bundle["trained_at_utc"],
        "seed": seed,
        "n_samples_requested": n_samples,
        "generation": gen_meta,
        "n_train": int(len(y_train)),
        "n_test": int(len(y_test)),
        "classes": classes,
        "accuracy": acc,
        "per_class_f1": per_class_f1,
        "confusion_matrix": cm,
        "confusion_matrix_labels": classes,
        "n_features": len(FEATURE_NAMES),
        "model": "RandomForestClassifier(n_estimators=400, class_weight='balanced_subsample')",
        "feature_note": "128 resampled up/down-stroke shape points + 7 scale-free ratios/slope + 8 Fourier "
                         "magnitudes -- see ml/dyno_classifier.py module docstring and FEATURE_NAMES.",
        "domain_shift_caveat": MODEL_CAVEAT,
    }
    with open(out_metrics, "w") as f:
        json.dump(metrics, f, indent=2)

    print(f"Generated {gen_meta['n_rows']} cards ({gen_meta['n_failed']} skipped of {gen_meta['n_attempted']} attempted)")
    print(f"Class counts: {gen_meta['class_counts']}")
    print(f"Train/test: {len(y_train)}/{len(y_test)} (seed={seed})")
    print(f"Accuracy: {acc:.4f}")
    for c in classes:
        print(f"  F1[{c}] = {per_class_f1[c]:.4f}")
    print(f"Saved model -> {out_model}\nSaved metrics -> {out_metrics}")
    return metrics


def _main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--train", action="store_true", help="regenerate the synthetic dataset and retrain")
    ap.add_argument("--demo", action="store_true", help="classify the 8 baked cards vs. their true label")
    ap.add_argument("--n-samples", type=int, default=3200)
    ap.add_argument("--seed", type=int, default=SEED)
    ap.add_argument("--params", default=str(DEFAULT_PARAMS_PATH))
    args = ap.parse_args(argv)

    with open(args.params) as f:
        params = json.load(f)

    if args.train:
        train(params, n_samples=args.n_samples, seed=args.seed)
    if args.demo or not args.train:
        for scenario in ("baseline", "recommendation"):
            for row in classify_baked_demo(scenario):
                match = "OK" if row["predicted_card_type"] == row["true_card_type"] else "MISS"
                print(f"[{match}] {scenario}:{row['key']:13s} true={row['true_card_type']:18s} "
                      f"pred={row['predicted_card_type']:18s} p={row['probabilities'][row['predicted_card_type']]:.2f}")


if __name__ == "__main__":
    _main()
